### ISSUE TITLE
Login Broken

### ISSUE THREAD

**Issue by Rambos-Ride** [EpicGames/EOS-Getting-Started#11]
When I try to login I get an invalid request on #12 Achievements Sample. Using 1.14sdk source.

**Comment by rajenki** [comment]
Hi there. Could you please clarify what error message you're seeing? I've updated the samples to support SDK 1.15.2 today, so perhaps you can give it another go using the latest SDK.

If it still doesn't work, would you mind sharing the log entries indicating what the error is?

Thanks,
Rajen

**Comment by Rambos-Ride** [comment]
Hello Rajen!

Thanks for contacting me. I can take a look at the new sample code was it
the C# or C samples?

Dan

**Comment by Rambos-Ride** [comment]
Rajen,

I got the updated samples from git and was able to easily get things
working!

Thanks so much for stepping up and making that happen!

Dan

**Comment by rajenki** [comment]
Hi Dan,

Awesome, that's great! The SDK itself has a lot of C samples, but the C# samples are limited, which is why I started this series to begin with. Glad it's all working for you now!

Rajen
