### ISSUE TITLE
EndSession() clear the StartSessionDelegateHandle instead of EndSessionDelegateHandle

### ISSUE THREAD

**Issue by Daemon34** [EpicGames/EOS-Getting-Started#17]
Hello,

I think there is a mistake in the EndSession() function here :
```c++
if (!Session->EndSession(SessionName))
{
        UE_LOG(LogTemp, Warning, TEXT("Failed to end session!"));
	Session->ClearOnEndSessionCompleteDelegate_Handle(StartSessionDelegateHandle);
        EndSessionDelegateHandle.Reset();
}
```
This clear the StartSessionDelegateHandle, but I think it should clear the EndSessionDelegateHandle

**Comment by SebBergy** [comment]
Yes, this is a mistake. Thank you for catching and reporting this mistake. I've just committed an update to the code here: https://github.com/EpicGames/EOS-Getting-Started/commit/0cf4ad6bb92c285efde069382566910a6a45e8da
