### ISSUE TITLE
code intelisense

### ISSUE THREAD

**Issue by farshidpakro** [EpicGames/EOS-Getting-Started#3]
hi 
i used  unreal 4_2.7 compile file to create game . and i try so many ide s. but none of them worked . please help . 

i do change so many setup . but steel i work n it . 
like-> cpp_properties.json
 thankyou

**Comment by SandeepSneedesh** [comment]
yes

**Comment by rajenki** [comment]
Hi, apologies for the massive delay in response. If you're still running into this issue, could you please clarify what the problem is you're seeing? This repo is for C# samples using the Epic Online Services SDK, so they will not work in Unreal Engine 4.27.

Thanks,
Rajen
